import { ToolConfig } from "./ToolSidebar";
import {
	Paintbrush,
	Eraser,
	PaintBucket,
	Pipette,
	Square,
	Circle,
	Minus,
	MousePointer,
	Lasso,
	Wand2,
	Pen,
	Pencil,
	Type,
	Hand,
	ZoomIn,
	ZoomOut,
	Stamp,
	Droplet,
	Blend,
	Sparkles,
	RectangleHorizontal,
	Hexagon,
	Spline,
	Move,
	Crop,
	Sun,
	Moon,
	Star as StarIcon,
} from "lucide-react";

export const tools: ToolConfig[] = [
	{
		id: "move",
		icon: Move,
		label: "Move Tool",
		shortcut: "V",
		description:
			"Move selected objects on the canvas. Hold Ctrl/Cmd for multi-select.",
		category: "selection",
	},
	{
		id: "select",
		icon: MousePointer,
		label: "Select Tool",
		shortcut: "A",
		description: "Select and manipulate individual objects on the canvas.",
		category: "selection",
	},
	{
		id: "marquee",
		icon: RectangleHorizontal,
		label: "Rectangular Marquee",
		shortcut: "M",
		description:
			"Create rectangular selections. Hold Shift for square, Alt for center origin.",
		category: "selection",
	},
	{
		id: "lasso",
		icon: Lasso,
		label: "Lasso Tool",
		shortcut: "L",
		description:
			"Draw freehand selections. Double-click or press Enter to close.",
		category: "selection",
	},
	{
		id: "magicwand",
		icon: Wand2,
		label: "Magic Wand",
		shortcut: "W",
		description: "Select areas of similar color. Adjust tolerance in options.",
		category: "selection",
	},
	{
		id: "crop",
		icon: Crop,
		label: "Crop Tool",
		shortcut: "C",
		description:
			"Trim the canvas to a specific area. Double-click or press Enter to apply.",
		category: "selection",
	},

	// Drawing Tools
	{
		id: "brush",
		icon: Paintbrush,
		label: "Brush Tool",
		shortcut: "B",
		description:
			"Paint strokes with customizable brushes. Use [ ] to adjust size.",
		category: "drawing",
	},
	{
		id: "pencil",
		icon: Pencil,
		label: "Pencil Tool",
		shortcut: "N",
		description: "Draw hard-edged lines. Ideal for pixel art and precise work.",
		category: "drawing",
	},
	{
		id: "eraser",
		icon: Eraser,
		label: "Eraser Tool",
		shortcut: "E",
		description: "Erase pixels to transparency. Hold Alt to sample background.",
		category: "drawing",
	},
	{
		id: "fill",
		icon: PaintBucket,
		label: "Paint Bucket",
		shortcut: "G",
		description:
			"Fill areas with foreground color. Adjust tolerance for color matching.",
		category: "drawing",
	},
	{
		id: "gradient",
		icon: Blend,
		label: "Gradient Tool",
		shortcut: "G",
		description:
			"Create smooth color transitions. Click and drag to define direction.",
		category: "drawing",
	},
	{
		id: "eyedropper",
		icon: Pipette,
		label: "Eyedropper",
		shortcut: "I",
		description:
			"Sample colors from canvas. Click for primary, Ctrl+click for secondary.",
		category: "drawing",
	},
	{
		id: "clone",
		icon: Stamp,
		label: "Clone Stamp",
		shortcut: "S",
		description:
			"Paint with pixels from another area. Alt+click to set source.",
		category: "drawing",
	},
	{
		id: "healing",
		icon: Droplet,
		label: "Healing Brush",
		shortcut: "J",
		description: "Remove imperfections by blending with surrounding pixels.",
		category: "drawing",
	},
	{
		id: "blur",
		icon: Sparkles,
		label: "Blur Tool",
		shortcut: "R",
		description: "Soften edges and reduce detail for depth of field effects.",
		category: "drawing",
	},
	{
		id: "dodge",
		icon: Sun,
		label: "Dodge Tool",
		shortcut: "O",
		description: "Lighten areas of the image by painting over them.",
		category: "drawing",
	},
	{
		id: "burn",
		icon: Moon,
		label: "Burn Tool",
		shortcut: "Shift+O",
		description: "Darken areas of the image by painting over them.",
		category: "drawing",
	},

	// Shape Tools
	{
		id: "rectangle",
		icon: Square,
		label: "Rectangle Tool",
		shortcut: "U",
		description: "Draw rectangles and squares. Hold Shift for perfect squares.",
		category: "shape",
	},
	{
		id: "ellipse",
		icon: Circle,
		label: "Ellipse Tool",
		shortcut: "U",
		description: "Draw ellipses and circles. Hold Shift for perfect circles.",
		category: "shape",
	},
	{
		id: "polygon",
		icon: Hexagon,
		label: "Polygon Tool",
		shortcut: "U",
		description: "Create multi-sided shapes. Set sides count in options.",
		category: "shape",
	},
	{
		id: "line",
		icon: Minus,
		label: "Line Tool",
		shortcut: "U",
		description: "Draw straight lines.",
		category: "shape",
	},
	{
		id: "star",
		icon: StarIcon,
		label: "Star Tool",
		shortcut: "U",
		description: "Create star shapes. Adjust number of points in options.",
		category: "shape",
	},
	{
		id: "pen",
		icon: Spline,
		label: "Pen Tool",
		shortcut: "Q",
		description: "Create precise paths with anchor points for complex shapes.",
		category: "shape",
	},
	{
		id: "text",
		icon: Type,
		label: "Text Tool",
		shortcut: "T",
		description:
			"Add and edit text layers. Click for point text, drag for area text.",
		category: "shape",
	},
	{
		id: "hand",
		icon: Hand,
		label: "Hand Tool",
		shortcut: "H",
		description: "Pan across the canvas. Hold Space for temporary access.",
		category: "navigation",
	},
	{
		id: "zoom",
		icon: ZoomIn,
		label: "Zoom Tool",
		shortcut: "Z",
		description: "Zoom in/out on canvas. Alt+click to zoom out.",
		category: "navigation",
	},
	{
		id: "undoZoom",
		icon: ZoomOut,
		label: "Undo Zoom",
		shortcut: "Shift+Z",
		description: "Restore previous zoom level.",
		category: "navigation",
	},
];
